apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new-nodeapp-h014
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-nodeapp-h014
    app.kubernetes.io/part-of: my-application
  name: new-nodeapp-h014
  namespace: karthik
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: new-nodeapp-h014
    weight: 100
status: {}
