apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new-nodeapp-h014
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-nodeapp-h014
    app.kubernetes.io/part-of: my-application
  name: new-nodeapp-h014
  namespace: karthik
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: new-nodeapp-h014
status:
  loadBalancer: {}
